language: rust

branches:
  only:
  - master
  # Github release tags (for example "v0.9" or "v0.9.1").
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  # Branch names endings with "-release" (for example "0.9.0-release").
  - /-release$/

rust:
- 1.34.0

env:
  global:
  - SODIUM_VERS=1.0.17
  - CARGO_INCREMENTAL=1
  - DEADLINKS_VERS=0.3.0

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty

before_install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget "https://github.com/jedisct1/libsodium/releases/download/$SODIUM_VERS/libsodium-$SODIUM_VERS.tar.gz" -t 5 -O "libsodium.tar.gz"
    tar xvf libsodium.tar.gz
    cd libsodium-$SODIUM_VERS
    ./configure --prefix=$HOME/.local
    make
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig

install:
- cargo deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
- rustup component add rustfmt-preview
- rustfmt -V
- rustup component add clippy-preview
- cargo clippy -V

script:
- cargo fmt -- --check
- cargo clippy --all-features --tests --examples -- -D warnings
- cargo check --all-features --tests --examples
- cargo test --tests --all-features
- cargo test --doc --all-features
- cargo run --example sodium_keypair > /dev/null
- cargo clean --doc && cargo doc --all-features --no-deps && cargo deadlinks --dir target/doc
- bash tests/e2e/key_util.sh

deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
