os: linux
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:fsgmhoward/shadowsocks-libev'
    packages:
      - libsodium-dev

branches:
  only:
    - master
    # Github release tags (for example "v0.9" or "v0.9.1").
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # Branch names endings with "-release" (for example "0.9.0-release").
    - /-release$/

language: rust
rust:
  - 1.41.0

env:
  global:
    - SODIUM_VERS=1.0.17
    - DEADLINKS_VERS=0.4.1

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.local
    - $TRAVIS_BUILD_DIR/target

before_install:
  # Install Node
  - nvm install 12 && nvm use 12
  # Install WASM toolchain
  - rustup target add wasm32-unknown-unknown
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

install:
  - cargo deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
  - rustup component add rustfmt
  - rustfmt -V
  - rustup component add clippy
  - cargo clippy -V

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-features --tests --examples -- -D warnings
  - cargo test --tests --all-features
  - cargo test --doc --all-features
  - cargo run --example sodium_keypair > /dev/null
  - cargo clean --doc && cargo doc --all-features --no-deps && cargo deadlinks --dir target/doc
  - bash tests/e2e/key_util.sh
  # Test WASM target
  - wasm-pack build --target nodejs $TRAVIS_BUILD_DIR/wasm
  - node $TRAVIS_BUILD_DIR/wasm/test.js

deploy:
  provider: pages
  local_dir: target/doc
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
